replicaCount: 1
appvolumemount:
  - name: config-volume
    mountPath: /etc/nginx/conf.d
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:


podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

sidecarContainers:
  - name: fbit-exporter
    args:
      - '--workdir=/fluent-bit/etc'
      - '--config=/fluent-bit/etc/conf/fluent-bit.conf'
    command:
      - /fluent-bit/bin/fluent-bit
    image: cr.fluentbit.io/fluent/fluent-bit:3.0.7-debug
    imagePullPolicy: IfNotPresent
    ports:
      - name: http-fbit
        containerPort: 2020
        protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/v1/health
        port: http-fbit
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http-fbit
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    volumeMounts:
      - name: config-fluentbit
        mountPath: /fluent-bit/etc/conf
      - mountPath: /var/log
        name: varlog
      - mountPath: /var/lib/docker/containers
        name: varlibdockercontainers
        readOnly: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

DefinedVolumes:
  - name: config-fluentbit
    configMap:
      name: config-fluentbit
  - hostPath:
      path: /var/log
      type: ''
    name: varlog
    readOnly: true
  - hostPath:
      path: /var/lib/docker/containers
      type: ''
    readOnly: true
    name: varlibdockercontainers
  - name: config-volume
    configMap:
      name: app-config